/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import daos.ParticipanteDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Participante;

/**
 *
 * @author otoniel.aalves
 */
public class FrmParticipanteConsulta extends javax.swing.JFrame {

    ParticipanteDao participanteDao = new ParticipanteDao();
    DefaultTableModel modelo;

    /**
     * Creates new form FrmParticipanteConsulta
     */
    public FrmParticipanteConsulta() {
        initComponents();
        carregaGrelha("");
    }

    //CARREGA GRELHA OTIMIZADA-------------------------------------------------
    public final void carregaGrelha(String pesquisa) {

        int contador = 0;
        modelo = (DefaultTableModel) grelha.getModel();
        modelo.setNumRows(0);

        List<Participante> lista;

        if (radNome.isSelected()) {
            lista = participanteDao.getPorNomeLike(pesquisa);
        } else if (radIgreja.isSelected()) {
            lista = participanteDao.getPorIgrejaLike(pesquisa);
        } else if (radPai.isSelected()) {
            lista = participanteDao.getPorPaiLike(pesquisa);
        } else if (radMae.isSelected()) {
            lista = participanteDao.getPorMaeLike(pesquisa);
        } else if (radContato.isSelected()) {
            lista = participanteDao.getPorContatoLike(pesquisa);
        } else {
            lista = participanteDao.getListagem();
        }
        
        for (Participante participante : lista) {

            modelo.addRow(new Object[]{
                participante.getId(),
                participante.getNome(),
                participante.getPai(),
                participante.getSexo(),
                participante.getCelular(),
                participante.getDataNascimento(),
                participante.getNomeContato(),
                participante.getTelefoneContato(),
                participante.getIgreja().getNomeIgreja(),
                contador

            });

            contador++;
        }

        lblQuantidade.setText("Localizados " + contador + " registros");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grelha = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        radNome = new javax.swing.JRadioButton();
        radIgreja = new javax.swing.JRadioButton();
        radPai = new javax.swing.JRadioButton();
        radMae = new javax.swing.JRadioButton();
        radContato = new javax.swing.JRadioButton();
        lblQuantidade = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ruler_pencil.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cross-button.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisa por:");

        lblTitulo.setBackground(new java.awt.Color(102, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Consulta de Participantes");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        grelha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Pai", "Sexo", "Celular", "Nascimento", "Contato", "Telefone", "Igreja"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grelha.setRowHeight(21);
        jScrollPane1.setViewportView(grelha);
        if (grelha.getColumnModel().getColumnCount() > 0) {
            grelha.getColumnModel().getColumn(0).setPreferredWidth(80);
            grelha.getColumnModel().getColumn(0).setMaxWidth(80);
            grelha.getColumnModel().getColumn(3).setPreferredWidth(90);
            grelha.getColumnModel().getColumn(3).setMaxWidth(90);
            grelha.getColumnModel().getColumn(4).setPreferredWidth(110);
            grelha.getColumnModel().getColumn(4).setMaxWidth(110);
            grelha.getColumnModel().getColumn(5).setPreferredWidth(100);
            grelha.getColumnModel().getColumn(5).setMaxWidth(100);
            grelha.getColumnModel().getColumn(7).setPreferredWidth(110);
            grelha.getColumnModel().getColumn(7).setMaxWidth(110);
        }

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clear.png"))); // NOI18N
        btnLimpar.setText("Limpar");

        buttonGroup1.add(radNome);
        radNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radNome.setForeground(new java.awt.Color(255, 255, 255));
        radNome.setSelected(true);
        radNome.setText("Nome");
        radNome.setOpaque(false);

        buttonGroup1.add(radIgreja);
        radIgreja.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radIgreja.setForeground(new java.awt.Color(255, 255, 255));
        radIgreja.setText("Igreja");
        radIgreja.setOpaque(false);

        buttonGroup1.add(radPai);
        radPai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radPai.setForeground(new java.awt.Color(255, 255, 255));
        radPai.setText("Pai");
        radPai.setOpaque(false);

        buttonGroup1.add(radMae);
        radMae.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radMae.setForeground(new java.awt.Color(255, 255, 255));
        radMae.setText("Mãe");
        radMae.setOpaque(false);

        buttonGroup1.add(radContato);
        radContato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radContato.setForeground(new java.awt.Color(255, 255, 255));
        radContato.setText("Contato");
        radContato.setOpaque(false);

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidade.setText("Quantidade 0 localizados");

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/person-add-outlineResultado.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setMinimumSize(new java.awt.Dimension(79, 33));
        btnNovo.setPreferredSize(new java.awt.Dimension(79, 33));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuantidade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(radNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radIgreja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radPai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radMae)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radContato)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar)
                    .addComponent(radNome)
                    .addComponent(radIgreja)
                    .addComponent(radPai)
                    .addComponent(radMae)
                    .addComponent(radContato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidade)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        if (grelha.getSelectedRowCount() > 0) {

            int codigo = (int) grelha.getValueAt(grelha.getSelectedRow(), 0);
            Participante participamente = participanteDao.retornaPorId(codigo);
            FrmParticipante frm = new FrmParticipante(participamente);
            frm.setVisible(true);            

        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        if (grelha.getSelectedRowCount() > 0) {
            int linha = grelha.getSelectedRow();

            // fim verifica se pede ser instalado
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o usuário", "confirm", JOptionPane.INFORMATION_MESSAGE);
            if (resposta == 0) {

                int codigo = (int) grelha.getValueAt(linha, 0);
                String nome = (String) grelha.getValueAt(linha, 1);
                if (participanteDao.excluir(codigo)) {

                    carregaGrelha("");

                    JOptionPane.showMessageDialog(this, nome + " - Excluido com sucesso.", "Sucesso", JOptionPane.WARNING_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Excluir usuário." + nome, "erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não foi excluido", "erro", JOptionPane.INFORMATION_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased

        // TODO add your handling code here:
        carregaGrelha(txtPesquisa.getText());
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        FrmParticipante frm = new FrmParticipante();
        frm.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
              carregaGrelha(txtPesquisa.getText());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParticipanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParticipanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParticipanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParticipanteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmParticipanteConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable grelha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radContato;
    private javax.swing.JRadioButton radIgreja;
    private javax.swing.JRadioButton radMae;
    private javax.swing.JRadioButton radNome;
    private javax.swing.JRadioButton radPai;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
